In [1]:
#One Sampled T-Test
import numpy as np
import pandas as pd
from scipy.stats import ttest_1samp
ages = pd.DataFrame({'ages':[32,34,29,29,22,39,38,37,38,36,30,26,22,22]})
print(ages)
ages_mean = np.mean(ages)
print(ages_mean)
tset, pval = ttest_1samp(ages, 30)
print(tset)
print('p-values',pval)
if pval < 0.05:    # alpha value is 0.05 or 5%
    print(" we are rejecting null hypothesis")
else:
    print("we are accepting null hypothesis")

    ages
0     32
1     34
2     29
3     29
4     22
5     39
6     38
7     37
8     38
9     36
10    30
11    26
12    22
13    22
ages    31.0
dtype: float64
[0.5973799]
('p-values', array([0.56051559]))
we are accepting null hypothesis

In [2]:
#Two Sampled T-Test
from scipy.stats import ttest_ind
import numpy as np
import pandas as pd
week1 = pd.read_csv("week1.csv")
week2 = pd.read_csv("week2.csv")

print(week1)
print("week2 data :-\n")
print(week2)
week1_mean = np.mean(week1)
week2_mean = np.mean(week2)
print("week1 mean value:",week1_mean)
print("week2 mean value:",week2_mean)
week1_std = np.std(week1)
week2_std = np.std(week2)
print("week1 std value:",week1_std)
print("week2 std value:",week2_std)
ttest,pval = ttest_ind(week1,week2)
print("p-value",pval)
if pval <0.05:
  print("we reject null hypothesis")
else:
  print("we accept null hypothesis")

         Data
0   12.152452
1   15.263790
2   18.268980
3   16.985980
4   18.425420
5   12.145470
6   18.125780
7   17.458760
8   15.689580
9   15.145780
10  16.245150
11  18.354280
12  14.654780
13  16.254860
14  14.689570
15  15.356240
16  14.524670
17  15.254780
18  18.567890
19  16.354640
20  19.254860
21  17.598340
22  16.525250
23  17.525450
24  19.021520
25  18.204680
26  17.201300
27  17.202020
28  18.201300
29  16.235360
30  17.279650
31  17.265890
32  14.201020
33  15.624100
34  17.230150
35  18.547050
36  17.506470
37  18.024750
38  12.035480
39  15.026240
40  15.452680
41  15.243590
42  18.254520
43  12.353640
44  16.324560
45  17.251540
46  12.154860
47  15.246121
48  17.256350
49  18.214120
week2 data :-

    Data_week2
0    23.215420
1    26.021020
2    24.021540
3    25.032540
4    26.541250
5    27.541250
6    21.032560
7    26.201550
8    28.365420
9    25.325602
10   24.879280
11   25.654800
12   25.698520
13   26.254180
14   28.362050
15   27.254120
16   26.215420
17   28.262010
18   24.025150
19   26.022250
20   27.632500
21   29.520150
22   28.302110
23   28.062450
24   27.521400
25   25.621020
26   27.025250
27   26.205010
28   28.254200
29   29.262400
30   25.632500
31   24.025350
32   28.360250
33   27.250150
34   28.284050
35   27.620150
36   29.302640
37   25.303620
38   26.025220
39   26.250320
40   25.033200
41   24.325020
42   28.326010
43   27.262020
44   28.026250
45   27.621020
46   28.302150
47   27.036520
48   25.302150
49   26.201250
('week1 mean value:', Data    16.347634
dtype: float64)
('week2 mean value:', Data_week2    26.576445
dtype: float64)
('week1 std value:', Data    1.900725
dtype: float64)
('week2 std value:', Data_week2    1.708221
dtype: float64)
('p-value', array([1.40507648e-48]))
we reject null hypothesis

In [4]:
# #One Sampled Z-test
# import pandas as pd
# from scipy import stats
# from statsmodels.stats import weightstats as stests
# df=pd.read_csv('Blood_pressure.csv')
# ztest ,pval = stests.ztest(df['bp_before'], x2=None, value=156)
# print(float(pval))
# if pval<0.05:
#     print("reject null hypothesis")
# else:
#     print("accept null hypothesis")